### PR TITLE
fix php 7.4 deprecations

### PR DESCRIPTION
**Pull request by andreybolonin**
https://wiki.php.net/rfc/deprecate_curly_braces_array_access

### CODE REVIEW

**Comment by Moskito89** [comment]
Hey guys, who can merge this PR?

**Comment by Seldaek** [comment]
@khanamiryan is the only one with access I believe. Definitely would need to be merged and a new tag created for PHP 7.4 support.

**Comment by Moskito89** [comment]
Thanks for the information Jordi, I absolutely agree. @andreybolonin could you have a look here please? :-)

**Comment by sprain** [comment]
Another *ping* on this one. Would be great if this could be merged. Thanks for your work!

**Comment by khanamiryan** [comment]
Sorry for late answer, guys

**Pull request merged**
